--<ScriptOptions statementTerminator="GO"/>

ALTER TABLE "ADMPRO"."CITY" DROP CONSTRAINT "CITY_COUNTRY_FK"
GO

ALTER TABLE "ADMPRO"."LODGING" DROP CONSTRAINT "LODGING_CITY_FK"
GO

ALTER TABLE "ADMPRO"."PRODUCT" DROP CONSTRAINT "PRODUCT_LODGING_FK"
GO

ALTER TABLE "ADMPRO"."PRODUCT" DROP CONSTRAINT "PRODUCT_SPECTACLE_FK"
GO

ALTER TABLE "ADMPRO"."PRODUCT" DROP CONSTRAINT "PRODUCT_TRANSPORT_FK"
GO

ALTER TABLE "ADMPRO"."SPECTACLE" DROP CONSTRAINT "SPECTACLE_CITY_FK"
GO

ALTER TABLE "ADMPRO"."TRANSPORT" DROP CONSTRAINT "TRANSPORT_CITY_FK"
GO

ALTER TABLE "ADMPRO"."TRANSPORT" DROP CONSTRAINT "TRANSPORT_CITY_FK1"
GO

ALTER TABLE "ADMPRO"."CITY" DROP CONSTRAINT "CITY_PK"
GO

ALTER TABLE "ADMPRO"."COUNTRY" DROP CONSTRAINT "COUNTRY_PK"
GO

ALTER TABLE "ADMPRO"."LODGING" DROP CONSTRAINT "LODGING_PK"
GO

ALTER TABLE "ADMPRO"."PRODUCT" DROP CONSTRAINT "PRODUCT_PK"
GO

ALTER TABLE "ADMPRO"."SPECTACLE" DROP CONSTRAINT "SPECTACLE_PK"
GO

ALTER TABLE "ADMPRO"."TRANSPORT" DROP CONSTRAINT "TRANSPORT_PK"
GO

DROP TABLE "ADMPRO"."CITY"
GO

DROP TABLE "ADMPRO"."COUNTRY"
GO

DROP TABLE "ADMPRO"."LODGING"
GO

DROP TABLE "ADMPRO"."PRODUCT"
GO

DROP TABLE "ADMPRO"."SPECTACLE"
GO

DROP TABLE "ADMPRO"."TRANSPORT"
GO

CREATE SCHEMA "ADMPRO"
GO

CREATE TABLE "ADMPRO"."CITY" (
		"Id" INT NOT NULL,
		"name" NVARCHAR(50) NULL,
		"country" INT NULL
	)
GO

CREATE TABLE "ADMPRO"."COUNTRY" (
		"Id" INT NOT NULL,
		"name" NVARCHAR(50) NULL
	)
GO

CREATE TABLE "ADMPRO"."LODGING" (
		"Id" INT NOT NULL,
		"arrival_date" DATE NULL,
		"departure_date" DATE NULL,
		"city" INT NULL,
		"nom_emp" NVARCHAR(50) NULL
	)
GO

CREATE TABLE "ADMPRO"."PRODUCT" (
		"Id" INT NOT NULL,
		"cod" NVARCHAR(20) NULL,
		"name" NVARCHAR(100) NULL,
		"description" NVARCHAR(200) NULL,
		"cost" NUMERIC(18 , 0) NULL,
		"image_ref" NVARCHAR(200) NULL,
		"transport_type" INT NULL,
		"spectacle_type" INT NULL,
		"lodging_type" INT NULL,
		"product_type" NVARCHAR(1) NULL
	)
GO

CREATE TABLE "ADMPRO"."SPECTACLE" (
		"Id" INT NOT NULL,
		"type" NVARCHAR(20) NULL,
		"spectacle_date" DATE NULL,
		"city" INT NULL,
		"nom_emp" NVARCHAR(50) NULL
	)
GO

CREATE TABLE "ADMPRO"."TRANSPORT" (
		"Id" INT NOT NULL,
		"source_city" INT NULL,
		"target_city" INT NULL,
		"depart_date" DATE NULL,
		"return_date" DATE NULL,
		"nom_emp" NVARCHAR(50) NULL,
		"tipo_trans" NVARCHAR(2) NULL
	)
GO

ALTER TABLE "ADMPRO"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY CLUSTERED
	("Id")
GO

ALTER TABLE "ADMPRO"."COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY CLUSTERED
	("Id")
GO

ALTER TABLE "ADMPRO"."LODGING" ADD CONSTRAINT "LODGING_PK" PRIMARY KEY CLUSTERED
	("Id")
GO

ALTER TABLE "ADMPRO"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY CLUSTERED
	("Id")
GO

ALTER TABLE "ADMPRO"."SPECTACLE" ADD CONSTRAINT "SPECTACLE_PK" PRIMARY KEY CLUSTERED
	("Id")
GO

ALTER TABLE "ADMPRO"."TRANSPORT" ADD CONSTRAINT "TRANSPORT_PK" PRIMARY KEY CLUSTERED
	("Id")
GO

ALTER TABLE "ADMPRO"."CITY" ADD CONSTRAINT "CITY_COUNTRY_FK" FOREIGN KEY
	("country")
	REFERENCES "ADMPRO"."COUNTRY"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."LODGING" ADD CONSTRAINT "LODGING_CITY_FK" FOREIGN KEY
	("city")
	REFERENCES "ADMPRO"."CITY"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."PRODUCT" ADD CONSTRAINT "PRODUCT_LODGING_FK" FOREIGN KEY
	("lodging_type")
	REFERENCES "ADMPRO"."LODGING"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."PRODUCT" ADD CONSTRAINT "PRODUCT_SPECTACLE_FK" FOREIGN KEY
	("spectacle_type")
	REFERENCES "ADMPRO"."SPECTACLE"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."PRODUCT" ADD CONSTRAINT "PRODUCT_TRANSPORT_FK" FOREIGN KEY
	("transport_type")
	REFERENCES "ADMPRO"."TRANSPORT"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."SPECTACLE" ADD CONSTRAINT "SPECTACLE_CITY_FK" FOREIGN KEY
	("city")
	REFERENCES "ADMPRO"."CITY"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."TRANSPORT" ADD CONSTRAINT "TRANSPORT_CITY_FK" FOREIGN KEY
	("source_city")
	REFERENCES "ADMPRO"."CITY"
	("Id")
	ON DELETE CASCADE
GO

ALTER TABLE "ADMPRO"."TRANSPORT" ADD CONSTRAINT "TRANSPORT_CITY_FK1" FOREIGN KEY
	("target_city")
	REFERENCES "ADMPRO"."CITY"
	("Id")
	ON DELETE CASCADE
GO

