//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 05:15:18 PM COT 
//


package hello.Wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for IRulesRuntimeContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IRulesRuntimeContext">
 *   &lt;complexContent>
 *     &lt;extension base="{http://runtime.openl.org}IRuntimeContext">
 *       &lt;sequence>
 *         &lt;element name="caProvince" type="{http://enumeration.rules.openl.org}CaProvincesEnum" minOccurs="0"/>
 *         &lt;element name="caRegion" type="{http://enumeration.rules.openl.org}CaRegionsEnum" minOccurs="0"/>
 *         &lt;element name="country" type="{http://enumeration.rules.openl.org}CountriesEnum" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://enumeration.rules.openl.org}CurrenciesEnum" minOccurs="0"/>
 *         &lt;element name="currentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lang" type="{http://enumeration.rules.openl.org}LanguagesEnum" minOccurs="0"/>
 *         &lt;element name="lob" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="region" type="{http://enumeration.rules.openl.org}RegionsEnum" minOccurs="0"/>
 *         &lt;element name="requestDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="usRegion" type="{http://enumeration.rules.openl.org}UsRegionsEnum" minOccurs="0"/>
 *         &lt;element name="usState" type="{http://enumeration.rules.openl.org}UsStatesEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IRulesRuntimeContext", namespace = "http://context.rules.openl.org", propOrder = {
    "caProvince",
    "caRegion",
    "country",
    "currency",
    "currentDate",
    "lang",
    "lob",
    "region",
    "requestDate",
    "usRegion",
    "usState"
})
public class IRulesRuntimeContext
    extends IRuntimeContext
{

    @XmlElementRef(name = "caProvince", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<CaProvincesEnum> caProvince;
    @XmlElementRef(name = "caRegion", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<CaRegionsEnum> caRegion;
    @XmlElementRef(name = "country", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<CountriesEnum> country;
    @XmlElementRef(name = "currency", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<CurrenciesEnum> currency;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar currentDate;
    @XmlElementRef(name = "lang", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<LanguagesEnum> lang;
    @XmlElementRef(name = "lob", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<String> lob;
    @XmlElementRef(name = "region", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<RegionsEnum> region;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestDate;
    @XmlElementRef(name = "usRegion", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<UsRegionsEnum> usRegion;
    @XmlElementRef(name = "usState", namespace = "http://context.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<UsStatesEnum> usState;

    /**
     * Gets the value of the caProvince property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CaProvincesEnum }{@code >}
     *     
     */
    public JAXBElement<CaProvincesEnum> getCaProvince() {
        return caProvince;
    }

    /**
     * Sets the value of the caProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CaProvincesEnum }{@code >}
     *     
     */
    public void setCaProvince(JAXBElement<CaProvincesEnum> value) {
        this.caProvince = value;
    }

    /**
     * Gets the value of the caRegion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CaRegionsEnum }{@code >}
     *     
     */
    public JAXBElement<CaRegionsEnum> getCaRegion() {
        return caRegion;
    }

    /**
     * Sets the value of the caRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CaRegionsEnum }{@code >}
     *     
     */
    public void setCaRegion(JAXBElement<CaRegionsEnum> value) {
        this.caRegion = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CountriesEnum }{@code >}
     *     
     */
    public JAXBElement<CountriesEnum> getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CountriesEnum }{@code >}
     *     
     */
    public void setCountry(JAXBElement<CountriesEnum> value) {
        this.country = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CurrenciesEnum }{@code >}
     *     
     */
    public JAXBElement<CurrenciesEnum> getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CurrenciesEnum }{@code >}
     *     
     */
    public void setCurrency(JAXBElement<CurrenciesEnum> value) {
        this.currency = value;
    }

    /**
     * Gets the value of the currentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrentDate() {
        return currentDate;
    }

    /**
     * Sets the value of the currentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrentDate(XMLGregorianCalendar value) {
        this.currentDate = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LanguagesEnum }{@code >}
     *     
     */
    public JAXBElement<LanguagesEnum> getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LanguagesEnum }{@code >}
     *     
     */
    public void setLang(JAXBElement<LanguagesEnum> value) {
        this.lang = value;
    }

    /**
     * Gets the value of the lob property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLob() {
        return lob;
    }

    /**
     * Sets the value of the lob property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLob(JAXBElement<String> value) {
        this.lob = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RegionsEnum }{@code >}
     *     
     */
    public JAXBElement<RegionsEnum> getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RegionsEnum }{@code >}
     *     
     */
    public void setRegion(JAXBElement<RegionsEnum> value) {
        this.region = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestDate(XMLGregorianCalendar value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the usRegion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UsRegionsEnum }{@code >}
     *     
     */
    public JAXBElement<UsRegionsEnum> getUsRegion() {
        return usRegion;
    }

    /**
     * Sets the value of the usRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UsRegionsEnum }{@code >}
     *     
     */
    public void setUsRegion(JAXBElement<UsRegionsEnum> value) {
        this.usRegion = value;
    }

    /**
     * Gets the value of the usState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UsStatesEnum }{@code >}
     *     
     */
    public JAXBElement<UsStatesEnum> getUsState() {
        return usState;
    }

    /**
     * Sets the value of the usState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UsStatesEnum }{@code >}
     *     
     */
    public void setUsState(JAXBElement<UsStatesEnum> value) {
        this.usState = value;
    }

}
