//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 05:15:18 PM COT 
//


package hello.Wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hello.Wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Descuentoxcategoria_QNAME = new QName("http://DefaultNamespace", "descuentoxcategoria");
    private final static QName _DescuentoxcategoriaResponse_QNAME = new QName("http://DefaultNamespace", "descuentoxcategoriaResponse");
    private final static QName _DescuentoxcategoriaCategoria_QNAME = new QName("http://DefaultNamespace", "categoria");
    private final static QName _SpreadsheetResultFieldsCoordinates_QNAME = new QName("http://calc.rules.openl.org", "fieldsCoordinates");
    private final static QName _SpreadsheetResultResults_QNAME = new QName("http://calc.rules.openl.org", "results");
    private final static QName _SpreadsheetResultRowNames_QNAME = new QName("http://calc.rules.openl.org", "rowNames");
    private final static QName _SpreadsheetResultColumnNames_QNAME = new QName("http://calc.rules.openl.org", "columnNames");
    private final static QName _IRulesRuntimeContextLob_QNAME = new QName("http://context.rules.openl.org", "lob");
    private final static QName _IRulesRuntimeContextCaRegion_QNAME = new QName("http://context.rules.openl.org", "caRegion");
    private final static QName _IRulesRuntimeContextLang_QNAME = new QName("http://context.rules.openl.org", "lang");
    private final static QName _IRulesRuntimeContextRegion_QNAME = new QName("http://context.rules.openl.org", "region");
    private final static QName _IRulesRuntimeContextCaProvince_QNAME = new QName("http://context.rules.openl.org", "caProvince");
    private final static QName _IRulesRuntimeContextUsState_QNAME = new QName("http://context.rules.openl.org", "usState");
    private final static QName _IRulesRuntimeContextCurrency_QNAME = new QName("http://context.rules.openl.org", "currency");
    private final static QName _IRulesRuntimeContextCountry_QNAME = new QName("http://context.rules.openl.org", "country");
    private final static QName _IRulesRuntimeContextUsRegion_QNAME = new QName("http://context.rules.openl.org", "usRegion");
    private final static QName _DescuentoxcategoriaResponseReturn_QNAME = new QName("http://DefaultNamespace", "return");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hello.Wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link String2PointMap }
     * 
     */
    public String2PointMap createString2PointMap() {
        return new String2PointMap();
    }

    /**
     * Create an instance of {@link IRuntimeContext }
     * 
     */
    public IRuntimeContext createIRuntimeContext() {
        return new IRuntimeContext();
    }

    /**
     * Create an instance of {@link ArrayOfAnyType }
     * 
     */
    public ArrayOfAnyType createArrayOfAnyType() {
        return new ArrayOfAnyType();
    }

    /**
     * Create an instance of {@link ArrayOfArrayOfAnyType }
     * 
     */
    public ArrayOfArrayOfAnyType createArrayOfArrayOfAnyType() {
        return new ArrayOfArrayOfAnyType();
    }

    /**
     * Create an instance of {@link Descuentoxcategoria }
     * 
     */
    public Descuentoxcategoria createDescuentoxcategoria() {
        return new Descuentoxcategoria();
    }

    /**
     * Create an instance of {@link DescuentoxcategoriaResponse }
     * 
     */
    public DescuentoxcategoriaResponse createDescuentoxcategoriaResponse() {
        return new DescuentoxcategoriaResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link SpreadsheetResult }
     * 
     */
    public SpreadsheetResult createSpreadsheetResult() {
        return new SpreadsheetResult();
    }

    /**
     * Create an instance of {@link IRulesRuntimeContext }
     * 
     */
    public IRulesRuntimeContext createIRulesRuntimeContext() {
        return new IRulesRuntimeContext();
    }

    /**
     * Create an instance of {@link String2PointMap.Entry }
     * 
     */
    public String2PointMap.Entry createString2PointMapEntry() {
        return new String2PointMap.Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Descuentoxcategoria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://DefaultNamespace", name = "descuentoxcategoria")
    public JAXBElement<Descuentoxcategoria> createDescuentoxcategoria(Descuentoxcategoria value) {
        return new JAXBElement<Descuentoxcategoria>(_Descuentoxcategoria_QNAME, Descuentoxcategoria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescuentoxcategoriaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://DefaultNamespace", name = "descuentoxcategoriaResponse")
    public JAXBElement<DescuentoxcategoriaResponse> createDescuentoxcategoriaResponse(DescuentoxcategoriaResponse value) {
        return new JAXBElement<DescuentoxcategoriaResponse>(_DescuentoxcategoriaResponse_QNAME, DescuentoxcategoriaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://DefaultNamespace", name = "categoria", scope = Descuentoxcategoria.class)
    public JAXBElement<String> createDescuentoxcategoriaCategoria(String value) {
        return new JAXBElement<String>(_DescuentoxcategoriaCategoria_QNAME, String.class, Descuentoxcategoria.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String2PointMap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://calc.rules.openl.org", name = "fieldsCoordinates", scope = SpreadsheetResult.class)
    public JAXBElement<String2PointMap> createSpreadsheetResultFieldsCoordinates(String2PointMap value) {
        return new JAXBElement<String2PointMap>(_SpreadsheetResultFieldsCoordinates_QNAME, String2PointMap.class, SpreadsheetResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfArrayOfAnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://calc.rules.openl.org", name = "results", scope = SpreadsheetResult.class)
    public JAXBElement<ArrayOfArrayOfAnyType> createSpreadsheetResultResults(ArrayOfArrayOfAnyType value) {
        return new JAXBElement<ArrayOfArrayOfAnyType>(_SpreadsheetResultResults_QNAME, ArrayOfArrayOfAnyType.class, SpreadsheetResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://calc.rules.openl.org", name = "rowNames", scope = SpreadsheetResult.class)
    public JAXBElement<ArrayOfString> createSpreadsheetResultRowNames(ArrayOfString value) {
        return new JAXBElement<ArrayOfString>(_SpreadsheetResultRowNames_QNAME, ArrayOfString.class, SpreadsheetResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://calc.rules.openl.org", name = "columnNames", scope = SpreadsheetResult.class)
    public JAXBElement<ArrayOfString> createSpreadsheetResultColumnNames(ArrayOfString value) {
        return new JAXBElement<ArrayOfString>(_SpreadsheetResultColumnNames_QNAME, ArrayOfString.class, SpreadsheetResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "lob", scope = IRulesRuntimeContext.class)
    public JAXBElement<String> createIRulesRuntimeContextLob(String value) {
        return new JAXBElement<String>(_IRulesRuntimeContextLob_QNAME, String.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaRegionsEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "caRegion", scope = IRulesRuntimeContext.class)
    public JAXBElement<CaRegionsEnum> createIRulesRuntimeContextCaRegion(CaRegionsEnum value) {
        return new JAXBElement<CaRegionsEnum>(_IRulesRuntimeContextCaRegion_QNAME, CaRegionsEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguagesEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "lang", scope = IRulesRuntimeContext.class)
    public JAXBElement<LanguagesEnum> createIRulesRuntimeContextLang(LanguagesEnum value) {
        return new JAXBElement<LanguagesEnum>(_IRulesRuntimeContextLang_QNAME, LanguagesEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionsEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "region", scope = IRulesRuntimeContext.class)
    public JAXBElement<RegionsEnum> createIRulesRuntimeContextRegion(RegionsEnum value) {
        return new JAXBElement<RegionsEnum>(_IRulesRuntimeContextRegion_QNAME, RegionsEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaProvincesEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "caProvince", scope = IRulesRuntimeContext.class)
    public JAXBElement<CaProvincesEnum> createIRulesRuntimeContextCaProvince(CaProvincesEnum value) {
        return new JAXBElement<CaProvincesEnum>(_IRulesRuntimeContextCaProvince_QNAME, CaProvincesEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsStatesEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "usState", scope = IRulesRuntimeContext.class)
    public JAXBElement<UsStatesEnum> createIRulesRuntimeContextUsState(UsStatesEnum value) {
        return new JAXBElement<UsStatesEnum>(_IRulesRuntimeContextUsState_QNAME, UsStatesEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurrenciesEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "currency", scope = IRulesRuntimeContext.class)
    public JAXBElement<CurrenciesEnum> createIRulesRuntimeContextCurrency(CurrenciesEnum value) {
        return new JAXBElement<CurrenciesEnum>(_IRulesRuntimeContextCurrency_QNAME, CurrenciesEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountriesEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "country", scope = IRulesRuntimeContext.class)
    public JAXBElement<CountriesEnum> createIRulesRuntimeContextCountry(CountriesEnum value) {
        return new JAXBElement<CountriesEnum>(_IRulesRuntimeContextCountry_QNAME, CountriesEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsRegionsEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://context.rules.openl.org", name = "usRegion", scope = IRulesRuntimeContext.class)
    public JAXBElement<UsRegionsEnum> createIRulesRuntimeContextUsRegion(UsRegionsEnum value) {
        return new JAXBElement<UsRegionsEnum>(_IRulesRuntimeContextUsRegion_QNAME, UsRegionsEnum.class, IRulesRuntimeContext.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://DefaultNamespace", name = "return", scope = DescuentoxcategoriaResponse.class)
    public JAXBElement<Double> createDescuentoxcategoriaResponseReturn(Double value) {
        return new JAXBElement<Double>(_DescuentoxcategoriaResponseReturn_QNAME, Double.class, DescuentoxcategoriaResponse.class, value);
    }

}
