//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 05:15:18 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://DefaultNamespace", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hello.Wsdl;
