//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 05:15:18 PM COT 
//


package hello.Wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegionsEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RegionsEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NCSA"/>
 *     &lt;enumeration value="EU"/>
 *     &lt;enumeration value="EMEA"/>
 *     &lt;enumeration value="APJ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RegionsEnum", namespace = "http://enumeration.rules.openl.org")
@XmlEnum
public enum RegionsEnum {

    NCSA,
    EU,
    EMEA,
    APJ;

    public String value() {
        return name();
    }

    public static RegionsEnum fromValue(String v) {
        return valueOf(v);
    }

}
