//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 05:15:18 PM COT 
//


package hello.Wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpreadsheetResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpreadsheetResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="columnNames" type="{http://DefaultNamespace}ArrayOfString" minOccurs="0"/>
 *         &lt;element name="fieldsCoordinates" type="{http://DefaultNamespace}string2PointMap" minOccurs="0"/>
 *         &lt;element name="results" type="{http://cxf.apache.org/arrays}ArrayOfArrayOfAnyType" minOccurs="0"/>
 *         &lt;element name="rowNames" type="{http://DefaultNamespace}ArrayOfString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpreadsheetResult", namespace = "http://calc.rules.openl.org", propOrder = {
    "columnNames",
    "fieldsCoordinates",
    "results",
    "rowNames"
})
public class SpreadsheetResult {

    @XmlElementRef(name = "columnNames", namespace = "http://calc.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<ArrayOfString> columnNames;
    @XmlElementRef(name = "fieldsCoordinates", namespace = "http://calc.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<String2PointMap> fieldsCoordinates;
    @XmlElementRef(name = "results", namespace = "http://calc.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<ArrayOfArrayOfAnyType> results;
    @XmlElementRef(name = "rowNames", namespace = "http://calc.rules.openl.org", type = JAXBElement.class)
    protected JAXBElement<ArrayOfString> rowNames;

    /**
     * Gets the value of the columnNames property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public JAXBElement<ArrayOfString> getColumnNames() {
        return columnNames;
    }

    /**
     * Sets the value of the columnNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public void setColumnNames(JAXBElement<ArrayOfString> value) {
        this.columnNames = value;
    }

    /**
     * Gets the value of the fieldsCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String2PointMap }{@code >}
     *     
     */
    public JAXBElement<String2PointMap> getFieldsCoordinates() {
        return fieldsCoordinates;
    }

    /**
     * Sets the value of the fieldsCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String2PointMap }{@code >}
     *     
     */
    public void setFieldsCoordinates(JAXBElement<String2PointMap> value) {
        this.fieldsCoordinates = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArrayOfAnyType }{@code >}
     *     
     */
    public JAXBElement<ArrayOfArrayOfAnyType> getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArrayOfAnyType }{@code >}
     *     
     */
    public void setResults(JAXBElement<ArrayOfArrayOfAnyType> value) {
        this.results = value;
    }

    /**
     * Gets the value of the rowNames property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public JAXBElement<ArrayOfString> getRowNames() {
        return rowNames;
    }

    /**
     * Sets the value of the rowNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public void setRowNames(JAXBElement<ArrayOfString> value) {
        this.rowNames = value;
    }

}
