//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.10 at 02:49:11 PM COT 
//


package validarTarjeta.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TarjetaValida" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tarjetaValida"
})
@XmlRootElement(name = "SalesOrderBPELResponse")
public class SalesOrderBPELResponse {

    @XmlElement(name = "TarjetaValida")
    protected boolean tarjetaValida;

    /**
     * Gets the value of the tarjetaValida property.
     * 
     */
    public boolean isTarjetaValida() {
        return tarjetaValida;
    }

    /**
     * Sets the value of the tarjetaValida property.
     * 
     */
    public void setTarjetaValida(boolean value) {
        this.tarjetaValida = value;
    }

}
