--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "ADMCYO"."CUSTOMER_ADDRESS" DROP CONSTRAINT "customer_address_address_FK";

ALTER TABLE "ADMCYO"."CUSTOMER_ADDRESS" DROP CONSTRAINT "customer_address_customer_FK";

ALTER TABLE "ADMCYO"."ORDER_ITEM" DROP CONSTRAINT "ORDER_ITEM_SALES_ORDER_FK";

ALTER TABLE "ADMCYO"."SALES_ORDER" DROP CONSTRAINT "SALES_ORDER_CUSTOMER_FK";

ALTER TABLE "ADMCYO"."ADDRESS" DROP CONSTRAINT "address_PK";

ALTER TABLE "ADMCYO"."CUSTOMER" DROP CONSTRAINT "customer_PK";

ALTER TABLE "ADMCYO"."ORDER_ITEM" DROP CONSTRAINT "ORDER_ITEM_PK";

ALTER TABLE "ADMCYO"."SALES_ORDER" DROP CONSTRAINT "SALES_ORDER_PK";

DROP TABLE "ADMCYO"."ADDRESS";

DROP TABLE "ADMCYO"."CUSTOMER";

DROP TABLE "ADMCYO"."CUSTOMER_ADDRESS";

DROP TABLE "ADMCYO"."ORDER_ITEM";

DROP TABLE "ADMCYO"."SALES_ORDER";

CREATE SCHEMA AUTHORIZATION "ADMCYO";

CREATE TABLE "ADMCYO"."ADDRESS" (
		"Id" NUMBER(20 , 0) NOT NULL,
		"street" NVARCHAR2(50) NOT NULL,
		"state" NVARCHAR2(50),
		"zip" NVARCHAR2(20),
		"country" NVARCHAR2(50),
		"address_type" NVARCHAR2(4),
		"city" NVARCHAR2(50)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "ADMCYO"."CUSTOMER" (
		"Id" NUMBER(20 , 0) NOT NULL,
		"document_type" NVARCHAR2(2),
		"document_number" NVARCHAR2(50),
		"first_name" NVARCHAR2(100),
		"last_name" NVARCHAR2(100),
		"phone_number" NVARCHAR2(20),
		"email" NVARCHAR2(50) NOT NULL,
		"password" NVARCHAR2(32),
		"creditcard_type" NVARCHAR2(4),
		"creditcard_number" NVARCHAR2(20),
		"status" NVARCHAR2(4),
		"category" NVARCHAR2(20)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "ADMCYO"."CUSTOMER_ADDRESS" (
		"address_id" NUMBER(20 , 0) NOT NULL,
		"customer_id" NUMBER(20 , 0) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "ADMCYO"."ORDER_ITEM" (
		"ID" NUMBER(20 , 0) NOT NULL,
		"PRODUCT_COD" NVARCHAR2(20),
		"PRODUCT_NAME" VARCHAR2(100),
		"PRICE" NUMBER(18 , 0),
		"QUANTITY" NUMBER(6 , 0),
		"ORDER_ID" NUMBER(20 , 0)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "ADMCYO"."SALES_ORDER" (
		"ID" NUMBER(20 , 0) NOT NULL,
		"ORDER_DATE" DATE,
		"PRICE" NUMBER(18 , 0),
		"STATUS" VARCHAR2(4),
		"COMMENTS" VARCHAR2(4000),
		"CUSTOMER_ID" NUMBER(20 , 0) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE INDEX "ADMCYO"."ORDER_ITEM_PK_IDX" ON "ADMCYO"."ORDER_ITEM" ("ID");

CREATE INDEX "ADMCYO"."SALES_ORDER_PK_IDX" ON "ADMCYO"."SALES_ORDER" ("ID");

CREATE INDEX "ADMCYO"."address_PK_IDX" ON "ADMCYO"."ADDRESS" ("Id");

CREATE INDEX "ADMCYO"."customer_PK_IDX" ON "ADMCYO"."CUSTOMER" ("Id");

ALTER TABLE "ADMCYO"."ADDRESS" ADD CONSTRAINT "address_PK" PRIMARY KEY
	("Id") USING INDEX "ADMCYO"."address_PK_IDX";

ALTER TABLE "ADMCYO"."CUSTOMER" ADD CONSTRAINT "customer_PK" PRIMARY KEY
	("Id") USING INDEX "ADMCYO"."customer_PK_IDX";

ALTER TABLE "ADMCYO"."ORDER_ITEM" ADD CONSTRAINT "ORDER_ITEM_PK" PRIMARY KEY
	("ID") USING INDEX "ADMCYO"."ORDER_ITEM_PK_IDX";

ALTER TABLE "ADMCYO"."SALES_ORDER" ADD CONSTRAINT "SALES_ORDER_PK" PRIMARY KEY
	("ID") USING INDEX "ADMCYO"."SALES_ORDER_PK_IDX";

ALTER TABLE "ADMCYO"."CUSTOMER_ADDRESS" ADD CONSTRAINT "customer_address_address_FK" FOREIGN KEY
	("address_id")
	REFERENCES "ADMCYO"."ADDRESS"
	("Id")
	ON DELETE CASCADE;

ALTER TABLE "ADMCYO"."CUSTOMER_ADDRESS" ADD CONSTRAINT "customer_address_customer_FK" FOREIGN KEY
	("customer_id")
	REFERENCES "ADMCYO"."CUSTOMER"
	("Id")
	ON DELETE CASCADE;

ALTER TABLE "ADMCYO"."ORDER_ITEM" ADD CONSTRAINT "ORDER_ITEM_SALES_ORDER_FK" FOREIGN KEY
	("ORDER_ID")
	REFERENCES "ADMCYO"."SALES_ORDER"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "ADMCYO"."SALES_ORDER" ADD CONSTRAINT "SALES_ORDER_CUSTOMER_FK" FOREIGN KEY
	("CUSTOMER_ID")
	REFERENCES "ADMCYO"."CUSTOMER"
	("Id")
	ON DELETE CASCADE;

